name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "新機能"
    labels:
      - "feat"
      - "feature"
  - title: "バグ修正"
    labels:
      - "fix"
      - "bugfix"
  - title: "ドキュメント"
    labels:
      - "documentation"
      - "docs"
  - title: "依存関係"
    labels:
      - "dependencies"
  - title: "その他の変更"
    labels:
      - "chore"
      - "refactor"
      - "ci"
      - "config"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feat"
      - "feature"
  patch:
    labels:
      - "fix"
      - "bugfix"
      - "documentation"
      - "chore"
  default: patch

template: |
  ## 変更内容

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
