catalog:
  '@biomejs/biome': 2.3.14
  '@commitlint/cli': 20.4.1
  '@commitlint/config-conventional': 20.4.1
  '@secretlint/secretlint-rule-preset-recommend': 11.3.1
  '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
  '@textlint/textlint-plugin-markdown': 15.5.1
  lefthook: 2.0.13
  remark: 15.0.1
  remark-cli: 12.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-lint: 10.0.1
  remark-preset-lint-consistent: 6.0.1
  remark-preset-lint-recommended: 7.0.1
  remark-toc: 9.0.0
  secretlint: 11.3.1
  textlint: 15.5.1
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.3.0
  textlint-rule-preset-ja-spacing: 2.4.3
  textlint-rule-preset-ja-technical-writing: 12.0.2
  textlint-rule-prh: 6.1.0

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

linkWorkspacePackages: true

nodeVersion: 24.11.0

onlyBuiltDependencies:
  - lefthook

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
